# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: lidar_frame.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Cluster(betterproto.Message):
    front_x: float = betterproto.float_field(1)
    front_y: float = betterproto.float_field(2)
    front_z: float = betterproto.float_field(3)
    extent_x: float = betterproto.float_field(4)
    extent_y: float = betterproto.float_field(5)
    extent_z: float = betterproto.float_field(6)


@dataclass
class Pointclouds(betterproto.Message):
    raw: bytes = betterproto.bytes_field(1)
    rows: int = betterproto.int32_field(2)
    cols: int = betterproto.int32_field(3)


@dataclass
class LidarFrame(betterproto.Message):
    timestamp_ns: int = betterproto.int64_field(1)
    timestamp_s: str = betterproto.string_field(2)
    clusters: List["Cluster"] = betterproto.message_field(3)
    object_label: str = betterproto.string_field(4)
    pointclouds: List["Pointclouds"] = betterproto.message_field(5)
    object_id: int = betterproto.int32_field(6)


@dataclass
class LidarDataset(betterproto.Message):
    frames: List["LidarFrame"] = betterproto.message_field(1)
